<?php

namespace Container10YdN0w;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zn1a_IAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zn1a.iA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zn1a.iA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ApiController::search' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\ApiController::matches' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator.O6aUYCb', 'get_ServiceLocator_O6aUYCbService', true],
            'App\\Controller\\InvitationController::list' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\InvitationController::respond' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\MatchingController::compute' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController::list' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController::create' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController::detail' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController::join' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController::invite' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController::delete' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController::leave' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\UserController::updateProfile' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\ApiController:search' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\ApiController:matches' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator.O6aUYCb', 'get_ServiceLocator_O6aUYCbService', true],
            'App\\Controller\\InvitationController:list' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\InvitationController:respond' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\MatchingController:compute' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController:list' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController:create' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController:detail' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController:join' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController:invite' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController:delete' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\SessionController:leave' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
            'App\\Controller\\UserController:updateProfile' => ['privates', '.service_locator.z0A7H.F', 'get_ServiceLocator_Z0A7H_FService', true],
        ], [
            'App\\Controller\\ApiController::search' => '?',
            'App\\Controller\\ApiController::matches' => '?',
            'App\\Controller\\AuthController::register' => '?',
            'App\\Controller\\InvitationController::list' => '?',
            'App\\Controller\\InvitationController::respond' => '?',
            'App\\Controller\\MatchingController::compute' => '?',
            'App\\Controller\\SessionController::list' => '?',
            'App\\Controller\\SessionController::create' => '?',
            'App\\Controller\\SessionController::detail' => '?',
            'App\\Controller\\SessionController::join' => '?',
            'App\\Controller\\SessionController::invite' => '?',
            'App\\Controller\\SessionController::delete' => '?',
            'App\\Controller\\SessionController::leave' => '?',
            'App\\Controller\\UserController::updateProfile' => '?',
            'App\\Controller\\ApiController:search' => '?',
            'App\\Controller\\ApiController:matches' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'App\\Controller\\InvitationController:list' => '?',
            'App\\Controller\\InvitationController:respond' => '?',
            'App\\Controller\\MatchingController:compute' => '?',
            'App\\Controller\\SessionController:list' => '?',
            'App\\Controller\\SessionController:create' => '?',
            'App\\Controller\\SessionController:detail' => '?',
            'App\\Controller\\SessionController:join' => '?',
            'App\\Controller\\SessionController:invite' => '?',
            'App\\Controller\\SessionController:delete' => '?',
            'App\\Controller\\SessionController:leave' => '?',
            'App\\Controller\\UserController:updateProfile' => '?',
        ]);
    }
}
