<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUjUXyDT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUjUXyDT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUjUXyDT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUjUXyDT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUjUXyDT\App_KernelDevDebugContainer([
    'container.build_hash' => 'UjUXyDT',
    'container.build_id' => '321255f4',
    'container.build_time' => 1780402830,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUjUXyDT');
